# Generated by Django 3.1.3 on 2020-11-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_bin', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(default='Default', max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_company', to='company_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='AccessFunc',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('import_products', models.BooleanField(default=True)),
                ('export_products', models.BooleanField(default=True)),
                ('import_kassa', models.BooleanField(default=True)),
                ('export_kassa', models.BooleanField(default=True)),
                ('movement', models.BooleanField(default=True)),
                ('application', models.BooleanField(default=True)),
                ('management', models.BooleanField(default=True)),
                ('reports', models.BooleanField(default=True)),
                ('profile', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_funs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
