# Generated by Django 3.1.3 on 2020-11-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessFunc',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('import_products', models.BooleanField(default=True)),
                ('export_products', models.BooleanField(default=True)),
                ('import_kassa', models.BooleanField(default=True)),
                ('export_kassa', models.BooleanField(default=True)),
                ('movement', models.BooleanField(default=True)),
                ('application', models.BooleanField(default=True)),
                ('management', models.BooleanField(default=True)),
                ('reports', models.BooleanField(default=True)),
                ('profile', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='company_bin',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
