# Generated by Django 3.1.3 on 2020-11-24 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_management', '0002_auto_20201124_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessfunc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_funs', to=settings.AUTH_USER_MODEL),
        ),
    ]
