# Generated by Django 3.1.3 on 2020-11-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_management', '0002_auto_20201124_0816'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accesses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='company_management.accessfunc'),
        ),
        migrations.AddField(
            model_name='account',
            name='active_account',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
