# Generated by Django 3.1.3 on 2020-11-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201124_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accesses',
        ),
    ]
