# Generated by Django 3.1.3 on 2020-12-03 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20201203_0609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImShoppingCartObject',
            fields=[
                ('im_shopping_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportProducts',
            fields=[
                ('im_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('im_shopping_car_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='im_shopping_car_obj', to='export_import_products.imshoppingcartobject')),
                ('import_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_product', to='products.companyproduct')),
            ],
        ),
    ]
