# Generated by Django 3.1.3 on 2020-11-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_management', '0003_accessfunc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Category',
            fields=[
                ('common_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('common_category_name', models.CharField(max_length=255)),
                ('common_category_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Each_Company_Category',
            fields=[
                ('each_company_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('each_company_category_name', models.CharField(max_length=255)),
                ('each_company_category_level', models.IntegerField()),
                ('each_company_category_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_company_category_company', to='company_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Each_Company_Product',
            fields=[
                ('each_company_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('each_company_product_name', models.CharField(max_length=255)),
                ('each_company_product_barcode', models.CharField(max_length=255)),
                ('each_company_product_import_price', models.IntegerField()),
                ('each_company_product_export_price', models.IntegerField()),
                ('each_company_product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_company_product_category', to='products.each_company_category')),
                ('each_company_product_in_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_company_product_company', to='company_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Each_Store_Product',
            fields=[
                ('each_store_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('each_store_product_amount', models.IntegerField()),
                ('each_store_product_in_company_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_store_product_in_company_product', to='products.each_company_product')),
            ],
        ),
        migrations.CreateModel(
            name='Common_Product',
            fields=[
                ('common_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('common_product_name', models.CharField(max_length=255)),
                ('common_product_barcode', models.CharField(max_length=255)),
                ('common_product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_product_category', to='products.common_category')),
            ],
        ),
    ]
