# Generated by Django 3.1.3 on 2020-11-30 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_level', models.IntegerField()),
                ('category_index_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_level', models.IntegerField()),
                ('category_index_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('category_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_company', to='company_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_barcode', models.CharField(max_length=255)),
                ('product_import_price', models.IntegerField(default=0)),
                ('product_export_price', models.IntegerField(default=0)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.companycategory')),
                ('product_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='each_company_product_company', to='company_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.IntegerField()),
                ('company_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_product', to='products.companyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CommonProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_barcode', models.CharField(max_length=255)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.commoncategory')),
            ],
        ),
    ]
