# Generated by Django 3.1.3 on 2020-12-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='category_index_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
